---
- apparmor-profiles:
    - '/usr/bin/onionshare'
    - '/usr/bin/onionshare-gui'
  users:
    - 'amnesia'
  commands:
    GETINFO:
      - 'version'
      - 'onions/current'
    ADD_ONION:
      - 'NEW:BEST Flags=BasicAuth Port=1,1 ClientAuth=onionshare'
      - (?:NEW\:RSA1024|RSA1024\:(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?)(?:| Flags\=BasicAuth) Port\=80,176([0-4][0-9]|50)(?:| ClientAuth\=onionshare)$
      - (?:NEW\:ED25519-V3|ED25519-V3\:(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?)(?:| Flags\=BasicAuth) Port\=80,176([0-4][0-9]|50)(?:| ClientAuth\=onionshare)$
    DEL_ONION:
      - '.+'
    GETCONF:
      - 'hiddenservicesinglehopmode'
  confs:
    __owningcontrollerprocess:
  events:
    SIGNAL:
      suppress: true
    CONF_CHANGED:
      suppress: true
    HS_DESC:
    STATUS_SERVER:
