inherit_from: ../.rubocop.yml

Layout/LineLength:
  IgnoredPatterns:
    # The first line of step definitions can be very long.
    - \A(Given|When|But|Then)\s+.*
    # Snapshot descriptions can be very long.
    - \A\s+description:\s+

Lint/AmbiguousRegexpLiteral:
  Description: This makes defining steps less verbose.
  Enabled: false
