# The directory where one stores `tails-amd64-*` sub-directories,
# like the ones downloaded with BitTorrent.
isos: FIXME
# The directory where build artifacts (e.g. the `.packages` file) land.
artifacts: FIXME
# A checkout of the `master` branch of the main Tails Git repository.
master_checkout: FIXME
# The checkout of the branch of the main Tails Git repository
# used to prepare the release (`stable` or `testing`).
release_checkout: FIXME
