inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  ExcludedMethods:
    # Cucumber
    - 'Given'
    - 'When'
    - 'Then'
    - 'But'
    - 'After'
    - 'AfterConfiguration'
    - 'Before'
    - 'BeforeFeature'

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: false

Style/GlobalVars:
  Description: Our test suite relies heavily on this design pattern.
  Enabled: false
